### ISSUE TITLE
IdentityModel dependency

### ISSUE THREAD

**Issue by theCuriousOne** [IdentityServer/IdentityServer3.AccessTokenValidation#141]
What are the reasons, the dependency of IdentityModel, is limited to versions >=1.9.2 && <2.0.0?
Can it be change/upgraded?

**Comment by leastprivilege** [comment]
1.x is for the "Katana wave" - 2.x for asp.net core/netstandard.

**Comment by zhouyongtao** [comment]
Thank you for solving my problem!

**Comment by Rzpeg** [comment]
Hello,
Because I share some internal (rest api) clients that use IdentityModel 2.* between AspNetCore (targeting full .net) and WebApi 2 projects, we had IdentityModel conflicts. As a solution I forked the repo and recompiled it against .net 4.6.1 and IdentityModel 2.*. (Missing extensions were ported from IdentityModel 1.*)

If anyone is experiencing the same issues, feel free to use the fork https://github.com/Rzpeg/IdentityServer3.AccessTokenValidation

Thanks, IdSrv team !
